- type: filestream
  id: production_json-log
  enabled: true
  paths:
    - /var/log/gitlab/gitlab-rails/production_json.log
  parsers:
    - ndjson:
        target: ""
        message_key: message

  json:
    keys_under_root: true

  processors:
    - decode_json_fields:
        fields: ["message"]
    - drop_event:
        when:
          or:
          - not.has_fields: ['remote_ip','username']
          - equals:
              remote_ip: ["192.168.1.2", "192.168.1.3"]
          - and:
              - not.contains:
                  controller: "Projects::MergeRequestsController"
                  action: "merge"
              - not.contains:
                  controller: "Repositories::GitHttpController"
                  action: "git_receive_pack"
              - not.contains:
                  controller: "Repositories::GitHttpController"
                  action: "info_refs"
              - not.contains:
                  controller: "Projects::MergeRequests::CreationsController"
                  action: "create"
              - not.equals:
                  "meta.caller_id": "POST /api/:version/internal/allowed"
                  "ua": "GitLab-Shell"
          - equals:
              "meta.remote_ip": "192.168.1.2"
          - contains:
              "ua": "gitlab-runner"
          - equals:
              status: 401
    - add_fields:
        target: '@metadata'
        fields:
          log_source: "production_json-log"
    - add_fields:
        target: 'track'
        fields:
          log_source: "production_json"
          repository: ""
          msg: ""
    - script:
        lang: javascript
        #file: ./remap.js
        source: >
          function process(event) {
            var data = event.Get('params');
            event.Rename('params','old_params')
            for (var field in data) {
              event.Put("params."+data[field].key, data[field].value)
            }
            event.Delete('old_params')
          }
    - move_fields:
        from: ""
        fields: ["meta.project","remote_ip","username","action","time","params","user_id","ua","controller","path"]
        to: "track."
        ignore_missing: true
    - rename:
        fields:
          - from: "track.meta.project"
            to: "track.project_path"
          - from: "track.action"
            to: "track.command"
          - from: "track.time"
            to: "track.action_time"
    - drop_fields:
        fields: ['graphql','/^db_(.*)$/','/^redis_(.*)$/','/^mem_/','/^duration_/','/^cpu_/','log','agent','/.*\_duration\_.*/',
          'pid','method','status','correlation_id',"meta.root_namespace","meta.client_id","request_urgency","format",
          "meta.feature_category","meta.user","meta.caller_id","meta.remote_ip","track.meta"]
        ignore_missing: true
    - add_tags:
        tags: [gitlab]
